name: Run Action
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
        type: string
env:
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
jobs:
  run-action:
    name: Run GH Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: vmware-labs/vmware-image-builder-action@${{ inputs.branch }}
        name: Verify and publish ${{ needs.get-chart.outputs.chart }}
